services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  backend:
    image: ${DOCKERHUB_USERNAME}/devops-b3-backend:latest
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      MONGO_URL: mongodb://mongo:27017/mydatabase
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - mongo

  frontend:
    image: ${DOCKERHUB_USERNAME}/devops-b3-frontend:latest
    restart: unless-stopped
    ports:
      - "80:8080"
    depends_on:
      - backend

volumes:
  mongo_data: